version: "3.8"

services:
  mysqldb:
    container_name: mysqldb1
    image: "mysql:8.3"
    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: db_docker
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3303:3306
    volumes:
      - ./db/:/var/lib/mysql/
    networks:
      springboot-mysql-net:

  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:9999
    depends_on:
      - mysqldb
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqldb1:3306/db_docker
      - spring.datasource.username=docker
      - spring.datasource.password=docker
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net: